### PR TITLE
Use feature detection instead of version detection

### PR DESCRIPTION
**Pull request by cclauss**
https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection

### CODE REVIEW

**Comment by piskvorky** [comment]
I agree in general -- feature detection is preferable when importing from a library, like your link shows.

In this particular case, we're checking a built-in and I'm not so sure. The current code seems both *clearer* (easier to read and understand) and *more future-proof* than your alternative (god only knows what `unicode` will mean in Python 4).

So mild -1 on this one.

**Comment by menshikh-iv** [comment]
@piskvorky  @cclauss From me -1 too, I think this change isn't needed.

**Comment by isamaru** [comment]
@cclauss Does this fix any particular problem with your configuration?

**Comment by cclauss** [comment]
No.  Closing.

**Pull request closed without merging**
