### PR TITLE
Include blog link in ReadMe

### PR DESCRIPTION
**Pull request by aneesh-joshi**
While trying to understand the usage and benefits of bounter, I found this blog on RaRe Tech.'s website very useful and could potentially help other developers and users.

### CODE REVIEW

**Comment by aneesh-joshi** [comment]
for some reason, my previous commit's file changes are also seen although they have been merged,

image

**Comment by menshikh-iv** [comment]
@aneesh-joshi can you merge current `master` to your branch? I think this will fix current problem.

**Comment by aneesh-joshi** [comment]
@menshikh-iv 
Thanks! 
That seems to have fixed it.
Do you have any idea why this happens? (never happened before)

**Comment by menshikh-iv** [comment]
@aneesh-joshi this is a side-effect of squash.
To avoid this, firstly, you should to update `master` and after - create a new branch based on it.

**Pull request merged**
